/**
 * Product interface
 *
 * Represents a full product in the system.
 * This interface is used to display existing products
 * and to receive data from the backend after create/update operations.
 */
export interface Product {
  id: number;           // Unique product ID (generated by the database)
  name: string;         // Product name
  price: number;        // Product price (decimal)
  description: string;  // Detailed product description
  isActive: boolean;    // Whether the product is active/available
}

/**
 * CatalogItem interface
 *
 * Represents a catalog item that combines product data
 * with inventory information. This is the aggregated view provided
 * by the GatewayBff that shows both product details and available quantity.
 */
export interface CatalogItem {
  productId: number;        // Unique product ID
  name: string;             // Product name
  description: string | null; // Product description (can be null)
  price: number;            // Product price (decimal)
  isActive: boolean;        // Whether the product is active/available
  availableQuantity: number; // Quantity available in inventory
}

/**
 * CreateProductRequest interface
 *
 * Defines the data required to create a new product.
 * Does not include the ID (generated by the server) or isActive (defaults to true).
 * Sent to the backend via a POST request.
 */
export interface CreateProductRequest {
  name: string;         // Name of the new product (required)
  price: number;        // Price of the new product (must be > 0)
  description: string;  // Description of the new product
}

/**
 * UpdateProductRequest interface
 *
 * Defines the data required to update an existing product.
 * Includes all editable product fields, including isActive.
 * Sent to the backend via a PUT request with the product ID in the URL.
 */
export interface UpdateProductRequest {
  name: string;         // Updated product name
  price: number;        // Updated product price
  description: string;  // Updated product description
  isActive: boolean;    // Updated active/inactive status
}
