<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageVersion Include="Confluent.Kafka" Version="2.6.1" />
    <PackageVersion Include="FirebaseAdmin" Version="3.0.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageVersion Include="Hangfire" Version="1.8.16" />
    <PackageVersion Include="Hangfire.PostgreSql" Version="1.20.9" />
    <PackageVersion Include="MailKit" Version="4.18.1" />
    <PackageVersion Include="MediatR" Version="12.4.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Facebook" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.12" />
    <PackageVersion Include="Microsoft.ML" Version="4.0.0" />
    <PackageVersion Include="Microsoft.ML.OnnxRuntime" Version="1.19.2" />
    <PackageVersion Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.19.2" />
    <PackageVersion Include="Microsoft.ML.TensorFlow" Version="4.0.0" />
    <PackageVersion Include="Microsoft.ML.Tokenizers" Version="0.22.0-preview.24378.1" />
    <PackageVersion Include="MimeKit" Version="4.18.1" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="RestSharp" Version="114.0.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.11.6" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageVersion Include="SixLabors.ImageSharp.Web" Version="3.1.5" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="StackExchange.Redis" Version="2.10.1" />
    <PackageVersion Include="Stripe.net" Version="43.12.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Twilio" Version="7.6.0" />
  </ItemGroup>
</Project>