namespace NotificationService.Models.Responses;

/// <summary>
/// Base response for notification operations
/// </summary>
public class NotificationResponse
{
    /// <summary>
    /// Whether the operation succeeded
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// ID of the created notification
    /// </summary>
    public long? NotificationId { get; set; }

    /// <summary>
    /// Confirmation or error message
    /// </summary>
    public string? Message { get; set; }

    /// <summary>
    /// External ID from the provider (Twilio SID, etc.)
    /// </summary>
    public string? ExternalId { get; set; }

    /// <summary>
    /// Additional details
    /// </summary>
    public Dictionary<string, string>? Details { get; set; }

    /// <summary>
    /// Timestamp of the operation
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// ID of the message generated by the provider
    /// </summary>
    public string? MessageId { get; set; }

    /// <summary>
    /// Notification status
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Error message (alias for Message)
    /// </summary>
    public string? Error
    {
        get => Success ? null : Message;
        set { if (!Success) Message = value; }
    }

    /// <summary>
    /// Creates an error response
    /// </summary>
    /// <param name="message">Error message</param>
    /// <returns>Response with an error</returns>
    public static NotificationResponse CreateError(string message)
    {
        return new NotificationResponse
        {
            Success = false,
            Message = message,
            Status = "failed"
        };
    }

    /// <summary>
    /// Creates a success response
    /// </summary>
    /// <param name="messageId">Message ID</param>
    /// <param name="message">Confirmation message</param>
    /// <returns>Response indicating success</returns>
    public static NotificationResponse CreateSuccess(string? messageId = null, string? message = null)
    {
        return new NotificationResponse
        {
            Success = true,
            MessageId = messageId,
            Message = message ?? "Notification sent successfully",
            Status = "sent"
        };
    }
}

/// <summary>
/// Response for sending multiple notifications
/// </summary>
public class BulkNotificationResponse
{
    /// <summary>
    /// Total number of requests
    /// </summary>
    public int TotalRequests { get; set; }

    /// <summary>
    /// Total number of notifications processed
    /// </summary>
    public int TotalProcessed { get; set; }

    /// <summary>
    /// Number of notifications sent successfully
    /// </summary>
    public int SuccessCount { get; set; }

    /// <summary>
    /// Number of failed notifications
    /// </summary>
    public int FailureCount { get; set; }

    /// <summary>
    /// Overall success of the operation
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// List of results for each notification in the bulk operation
    /// </summary>
    public List<BulkNotificationResult> Results { get; set; } = new();

    /// <summary>
    /// Total processing time
    /// </summary>
    public TimeSpan ProcessingTime { get; set; }
}

/// <summary>
/// Result for a single notification within a bulk operation
/// </summary>
public class BulkNotificationResult
{
    /// <summary>
    /// Recipient
    /// </summary>
    public required string Recipient { get; set; }

    /// <summary>
    /// Whether the send succeeded
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Error message (if any)
    /// </summary>
    public string? Error { get; set; }

    /// <summary>
    /// Message ID
    /// </summary>
    public string? MessageId { get; set; }

    /// <summary>
    /// External ID from the provider
    /// </summary>
    public string? ExternalId { get; set; }

    /// <summary>
    /// Notification status
    /// </summary>
    public string? Status { get; set; }
}

/// <summary>
/// Status of a notification
/// </summary>
public class NotificationStatusResponse
{
    /// <summary>
    /// Notification ID
    /// </summary>
    public long NotificationId { get; set; }

    /// <summary>
    /// Current status
    /// </summary>
    public NotificationStatus Status { get; set; }

    /// <summary>
    /// Notification type
    /// </summary>
    public NotificationType Type { get; set; }

    /// <summary>
    /// Recipient
    /// </summary>
    public required string Recipient { get; set; }

    /// <summary>
    /// Subject/title
    /// </summary>
    public required string Subject { get; set; }

    /// <summary>
    /// Creation date
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Sent date
    /// </summary>
    public DateTime? SentAt { get; set; }

    /// <summary>
    /// Delivered/read date
    /// </summary>
    public DateTime? DeliveredAt { get; set; }

    /// <summary>
    /// Number of attempts
    /// </summary>
    public int RetryCount { get; set; }

    /// <summary>
    /// Last error message
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// External provider ID
    /// </summary>
    public string? ExternalId { get; set; }

    /// <summary>
    /// Whether the send completed successfully
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// Last updated date
    /// </summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Error message (if any)
    /// </summary>
    public string? Error { get; set; }
}

/// <summary>
/// Response with a list of notifications
/// </summary>
public class NotificationListResponse
{
    /// <summary>
    /// List of notifications
    /// </summary>
    public List<NotificationStatusResponse> Notifications { get; set; } = new();

    /// <summary>
    /// Total number of items
    /// </summary>
    public int TotalCount { get; set; }

    /// <summary>
    /// Current page
    /// </summary>
    public int Page { get; set; }

    /// <summary>
    /// Items per page
    /// </summary>
    public int PageSize { get; set; }

    /// <summary>
    /// Total number of pages
    /// </summary>
    public int TotalPages { get; set; }
}

/// <summary>
/// Response with notification statistics
/// </summary>
public class NotificationStatsResponse
{
    /// <summary>
    /// Statistics by notification type
    /// </summary>
    public Dictionary<NotificationType, TypeStats> TypeStats { get; set; } = new();

    /// <summary>
    /// Statistics by status
    /// </summary>
    public Dictionary<NotificationStatus, int> StatusStats { get; set; } = new();

    /// <summary>
    /// Total notifications in the period
    /// </summary>
    public int TotalNotifications { get; set; }

    /// <summary>
    /// Overall success rate
    /// </summary>
    public double SuccessRate { get; set; }

    /// <summary>
    /// Statistics period
    /// </summary>
    public DateRange Period { get; set; } = new();

    /// <summary>
    /// Average delivery time
    /// </summary>
    public TimeSpan? AverageDeliveryTime { get; set; }
}

/// <summary>
/// Statistics for a notification type
/// </summary>
public class TypeStats
{
    /// <summary>
    /// Total number for this type
    /// </summary>
    public int Total { get; set; }

    /// <summary>
    /// Number of successes
    /// </summary>
    public int Success { get; set; }

    /// <summary>
    /// Number of failures
    /// </summary>
    public int Failed { get; set; }

    /// <summary>
    /// Success rate
    /// </summary>
    public double SuccessRate { get; set; }

    /// <summary>
    /// Average send time
    /// </summary>
    public TimeSpan? AverageTime { get; set; }
}

/// <summary>
/// Date range for statistics
/// </summary>
public class DateRange
{
    /// <summary>
    /// Start date
    /// </summary>
    public DateTime From { get; set; }

    /// <summary>
    /// End date
    /// </summary>
    public DateTime To { get; set; }
}

/// <summary>
/// Response for the service's health check
/// </summary>
public class NotificationHealthResponse
{
    /// <summary>
    /// Overall service status
    /// </summary>
    public bool IsHealthy { get; set; }

    /// <summary>
    /// Service version
    /// </summary>
    public required string Version { get; set; }

    /// <summary>
    /// Check timestamp
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Status of external providers
    /// </summary>
    public Dictionary<string, ProviderHealth> Providers { get; set; } = new();

    /// <summary>
    /// Database status
    /// </summary>
    public bool DatabaseHealthy { get; set; }

    /// <summary>
    /// Redis cache status
    /// </summary>
    public bool CacheHealthy { get; set; }

    /// <summary>
    /// Queued notifications
    /// </summary>
    public int QueuedNotifications { get; set; }

    /// <summary>
    /// Jobs being processed
    /// </summary>
    public int ProcessingJobs { get; set; }
}

/// <summary>
/// Status of a notification provider
/// </summary>
public class ProviderHealth
{
    /// <summary>
    /// Provider name
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Whether the provider is operational
    /// </summary>
    public bool IsHealthy { get; set; }

    /// <summary>
    /// Last check performed
    /// </summary>
    public DateTime LastCheck { get; set; }

    /// <summary>
    /// Error messages
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Response time
    /// </summary>
    public TimeSpan? ResponseTime { get; set; }
}
